### ISSUE TITLE
Menu is growing for each import

### ISSUE THREAD

**Issue by emorling** [Webcreations907/WBC-Importer-extension#48] opened 2015-10-17 10:06 UTC
Each time I do an import the Primary Menu in Wordpress is growing with a new set of items. Any ideas how to fix this?

**Comment by Webcreations907** [comment] 2016-02-20 08:15
Hello,
Sorry I've been so far behind, been hard to get in here. 

The WordPress Importer plugin is actually the cause of the menus issue being reimported each time. They have some filters in there that you could use to check to see if the menu items are already imported.

I'll close this since, but if you have any further questions about it just let me know.

Thanks

**Closed as completed by Webcreations907** 2016-02-20 08:15 UTC
